apiVersion: build.openshift.io/v1
kind: BuildConfig
metadata:
  name: devops-test-node-backend
  namespace: ci-cd
spec:
  output:
    to:
      kind: ImageStreamTag
      name: 'devops-test-node-backend:latest'
  postCommit:
    script: npm test
  runPolicy: Serial
  source:
    git:
      uri: 'https://github.com/feitais/PipelineScriptsBackendProject.git'
    type: Git
  strategy:
    sourceStrategy:
      env:
        - name: NPM_MIRROR
      from:
        kind: ImageStreamTag
        name: 'nodejs:8'
        namespace: openshift
    type: Source
  triggers:
    - type: ConfigChange
    - github:
        secret: Ye1q8snvXaSJMKfURNyPq0rheQVdcbRdDRViYqOy
      type: GitHub
    - generic:
        secret: TGuEoRuHNgp4WOIhlj5F7BNFMdd6Ewc5XAXPuxws
      type: Generic

