apiVersion: batch/v1
kind: Job
metadata:
  name: maven-backend-v1-depcheck
spec:
  template:
    spec:
      volumes:
        - name: workspace
          persistentVolumeClaim:
            claimName: pvc-cache-maven
        - name: dependency-data-dir
          persistentVolumeClaim:
            claimName: owasp-datadir
      restartPolicy: Never
      containers:
      - args:
          - '--scan'
          - '/src/Openshift/Maven'
          - '--format'
          - 'ALL'
          - '--project'
          - 'dependency-check scan: /src/Openshift/Maven'
          - '--out'
          -  '/src/Openshift/Maven/report'
          - '--noupdate'
        image: "owasp/dependency-check:5.3.2"
        name: maven-backend-v1-depcheck
        volumeMounts:
          - mountPath: /src
            name: workspace
          - mountPath: /usr/share/dependency-check/data
            name: dependency-data-dir
  backoffLimit: 3
