apiVersion: batch/v1
kind: Job
metadata:
  name: dependency-update
spec:
  template:
    spec:
      volumes:
        - name: dependency-data-dir
          persistentVolumeClaim:
            claimName: owasp-datadir
      restartPolicy: Never
      containers:
      - args:
          - '--updateonly'
        image: "owasp/dependency-check:5.3.2"
        name: dependency-check
        volumeMounts:
          - mountPath: /usr/share/dependency-check/data
            name: dependency-data-dir
  backoffLimit: 3
