#kind: Namespace
#apiVersion: v1
#metadata:
# name: nodejs
#spec:
# finalizers:
#  - kubernetes
#---
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  annotations:
    #kubernetes.io/ingress.class: addon-http-application-routing
    kubernetes.io/ingress.class: nginx
  name: nodejs
  namespace: nodejs
  labels:
    app: nodejs
    role: principal
spec:
  rules:
    - host: nodejs.aks.linux4sysadmin.com.br
      http:
        paths:
          - backend:
              serviceName: nodejs-service
              servicePort: 8080
            path: /
  tls:
    - hosts:
        - nodejs.aks.linux4sysadmin.com.br
---
apiVersion: v1
kind: Service
metadata:
 name: nodejs-service
 namespace: nodejs
 labels:
   app: nodejs
   role: principal
spec:
 selector:
   app: nodejs
   role: blue
 ports:
  - port: 8080
    targetPort: 3000
---
apiVersion: v1
data:
  .dockerconfigjson: eyJhdXRocyI6eyJjbW90dGEyMDE2LmF6dXJlY3IuaW8iOnsidXNlcm5hbWUiOiJjbW90dGEyMDE2IiwicGFzc3dvcmQiOiJBbWxUVG9jbWlaSldPNGVqODZXWC9NNXY5NlFBdGZ1dyIsImF1dGgiOiJZMjF2ZEhSaE1qQXhOanBCYld4VVZHOWpiV2xhU2xkUE5HVnFPRFpYV0M5Tk5YWTVObEZCZEdaMWR3PT0ifX19
kind: Secret
metadata:
  creationTimestamp: null
  name: acrregcred
  namespace: nodejs
  labels:
    app: nodejs
type: kubernetes.io/dockerconfigjson