apiVersion: v1
kind: Service
metadata:
 name: nodejs-service
 labels:
   app: nodejs
spec:
 type: LoadBalancer
 selector:
  component: web
 ports:
  - port: 8080
    targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: nodejs
 name: nodejs
 annotations:  
   template.alpha.openshift.io/wait-for-ready: 'true'
spec:
 replicas: 1
 selector:
  matchLabels:
   component: web
 template:
  metadata:
   labels:
    component: web
    app: nodejs
  spec:
   containers: 
    - name: nodejs
      image: cmotta2016/k8s-nodejs
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 1024Mi
      ports:
       - containerPort: 3000
