kind: Namespace
apiVersion: v1
metadata:
 name: nodejs
spec:
 finalizers:
  - kubernetes
---
# Create secret with kubectl create secret docker-registry regcred --docker-server=<your-registry-server> --docker-username=<your-name> --docker-password=<your-pword> --docker-email=<your-email>
apiVersion: v1
kind: Secret
metadata:
  name: regcred
  namespace: nodejs
data:
  .dockerconfigjson: eyJhdXRocyI6eyJyZWdpc3RyeS5hcHBzLmxpbnV4NHN5c2FkbWluLmNvbS5iciI6eyJ1c2VybmFtZSI6ImFkbWluIiwicGFzc3dvcmQiOiJhZG1pbiIsImF1dGgiOiJZV1J0YVc0NllXUnRhVzQ9In19fQ==
type: kubernetes.io/dockerconfigjson
---
apiVersion: v1
kind: Service
metadata:
 name: nodejs-service
 namespace: nodejs
 labels:
   app: nodejs
spec:
 type: LoadBalancer
 selector:
   app: nodejs
 ports:
  - port: 8080
    targetPort: 3000
    #nodePort: 30523
---
apiVersion: apps/v1
kind: Deployment
metadata:
 labels:
   app: nodejs
 name: nodejs
 namespace: nodejs
 annotations:  
   template.alpha.openshift.io/wait-for-ready: 'true'
spec:
 replicas: 1
 selector:
  matchLabels:
   app: nodejs
 template:
  metadata:
   labels:
    app: nodejs
  spec:
   imagePullSecrets:
    - name: regcred
   containers: 
    - name: nodejs
      image: 129.213.187.72:5003/node/k8s-nodejs:latest
      resources:
        limits:
          cpu: '1'
          memory: 1Gi
        requests:
          cpu: 100m
          memory: 150Mi
      ports:
       - containerPort: 3000
      livenessProbe:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 10
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
      readinessProbe:
        httpGet:
          path: /
          port: 3000
          scheme: HTTP
        initialDelaySeconds: 30
        timeoutSeconds: 2
        periodSeconds: 10
        successThreshold: 1
        failureThreshold: 3
---
apiVersion: autoscaling/v2beta2
kind: HorizontalPodAutoscaler
metadata:
  name: nodejs
  namespace: nodejs
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: nodejs
  minReplicas: 1
  maxReplicas: 10
  metrics:
  - type: Resource
    resource:
      name: cpu
      target:    
        type: Utilization
        averageUtilization: 50
